version: '3'
services:

  certbot:
    build: .
    environment:
      - TZ=Europe/Berlin
    volumes:
      - certs:/etc/letsencrypt
      - var:/var/lib/letsencrypt
      - www:/var/www/.well-known
      - secrets:/run/secrets/hosting.de

volumes:
  certs:
  www:
  secrets:
  var: